### ISSUE TITLE
Disable clang-format reordering includes

### ISSUE THREAD

**Issue by tigercosmos** [solvcon/modmesh#351]
Prevent clang-format reordering the includes. 

see discussion here: https://github.com/solvcon/modmesh/pull/349#discussion_r1629451567

**Comment by tigercosmos** [comment]
Actually, we already defined it
https://github.com/solvcon/modmesh/blob/ac4cd11dc9fc26d383cb41ab1646255516d39727/.clang-format#L135

I think it's my VSCode issue, seems the extension just ignores that flag.

**Comment by yungyuc** [comment]
> I think it's my VSCode issue, seems the extension just ignores that flag.

This is a good finding and we can point others to your comment
